### ISSUE TITLE
Does the app still work in 2024 with the latest Ubuntu and node js 23.x?

### ISSUE THREAD

**Issue by SugarRayLua** [make-install-linux/Kindle-for-ubuntu#1]
Hi-- thanks for the very useful app!

I am running Ubuntu Noble 24.04 (x86_64) via Tuxedo OS distribution and followed your install instructions after installing node js 23.x.

The installation script though did generate multiple npm errors (see attached debug log). 

The application though did show up on my app launcher, but when I tried to launch it nothing happened. Thus, I was wondering if it was compatible with the current version of Ubuntu and node js.

Thank you :-)
[2024-11-15T20_28_21_722Z-debug-0.log](https://github.com/user-attachments/files/17781081/2024-11-15T20_28_21_722Z-debug-0.log)

**Comment by Abhishek99588** [comment]
I tried to run the function as instructed but it is showing this error.. please help

![Screenshot from 2024-12-12 19-26-31](https://github.com/user-attachments/assets/0266ba32-ca9d-48fa-9828-fcad85c5df60)

**Comment by Dpbm** [comment]
Sorry about that guys! It was a side project of mine that was kinda abandoned.

Thanks for open this issue and reporting these errors. Please, let me know if it keeps happening.

**Comment by Abhishek99588** [comment]
Thank you for your reply.. and as you mentioned above that the project was
abandoned. Are you going to fix it or not??

**Comment by Dpbm** [comment]
Yeah, I fixed in this new PR. It should be working by now.

Make sure to clean all the files from the version and then try this new one.

**Comment by SugarRayLua** [comment]
Good Evening, @Dpbm, and thanks for working on this again!

Unfortunately, for some reason, it still does not work for me. I removed the files and my prior Kindle directory and had the same problem-- app shows up under my application, but after clicking it nothing happens. 

Any other suggestions or should I post some sort of an additional log?

Thanks!

**Comment by Dpbm** [comment]
During my tests, I had a similar issue. For me, it was solved after running the `uninstall.sh` script and installing it again.
It was happening because of some sort of caching in the gnome applications hub.

So try running:

```bash
cd ~/kindle
chmod +x uninstall.sh
./uninstall.sh
cd ~
```

then follow the installation steps again.

```bash
mkdir -p ~/kindle
git clone https://github.com/Dpbm/Kindle-for-ubuntu.git ~/kindle
cd ~/kindle
chmod +x ./install.sh
./install.sh
```

`Note: Keep in mind that running the uninstall script the files/directories ~/kindle/, ~/.local/share/icons/Kindle.png and ~/.local/share/applications/kindle.desktop will be permanently deleted. Ensure that there're no important files in this list.`

**Comment by SugarRayLua** [comment]
Thanks again, @Dpmb for the advice.

Unfortunately, after going through those steps multiple times, I can't get the app to run (just starts to boot up and shoes me the Kindle app but then doesn't do anything). 

Do you think it makes a different that I am on KDE rather than Gnome desktop??

**Comment by SugarRayLua** [comment]
@Dpmb,
I tried running from the command line and got this:
```
mikes@tuxedo-os:~/kindle$ ./kindle.sh

> kindle@1.0.0 start
> node_modules/.bin/electron main.js

[53832:1213/161219.267231:FATAL:setuid_sandbox_host.cc(163)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/mikes/kindle/node_modules/electron/dist/chrome-sandbox is owned by root and has mode 4755.
/home/mikes/kindle/node_modules/electron/dist/electron exited with signal SIGTRAP
mikes@tuxedo-os:~/kindle$ [53835:0100/000000.303134:ERROR:zygote_linux.cc(678)] write: Broken pipe (32)

mikes@tuxedo-os:~/kindle$ sudo ./kindle.sh
[sudo] password for mikes: 
./kindle.sh: line 3: cd: /root/kindle: No such file or directory
./kindle.sh: line 4: npm: command not found
mikes@tuxedo-os:~/kindle$ 
```
(Not sure if that helps anything)

**Comment by SugarRayLua** [comment]
@Dpmb,
I tried running from the command line and got this:
```
mikes@tuxedo-os:~/kindle$ ./kindle.sh

> kindle@1.0.0 start
> node_modules/.bin/electron main.js

[53832:1213/161219.267231:FATAL:setuid_sandbox_host.cc(163)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/mikes/kindle/node_modules/electron/dist/chrome-sandbox is owned by root and has mode 4755.
/home/mikes/kindle/node_modules/electron/dist/electron exited with signal SIGTRAP
mikes@tuxedo-os:~/kindle$ [53835:0100/000000.303134:ERROR:zygote_linux.cc(678)] write: Broken pipe (32)

mikes@tuxedo-os:~/kindle$ sudo ./kindle.sh
[sudo] password for mikes: 
./kindle.sh: line 3: cd: /root/kindle: No such file or directory
./kindle.sh: line 4: npm: command not found
mikes@tuxedo-os:~/kindle$ 
```
(Not sure if that helps anything)

**Comment by Abhishek99588** [comment]
I am having the same issue.. I followed your mentioned steps . And uninstalled and installed it again.. the icon is visible but nothing is happening

**Comment by Dpbm** [comment]
@SugarRayLua I tested the application in the same scenario as you described but on a `Kubuntu` and got the same issue. The solution I found was to add the `--no-sandbox` flag in the start script.

---

I've just updated the script, so I recommend you to run the `uninstall.sh` and then reinstall it again. Let me know the issue still there.

**Comment by Dpbm** [comment]
@Abhishek99588 are you using KDE as @SugarRayLua?

Could you, please, run the `~/kindle/kindle.sh` script and show the logs here?

**Comment by SugarRayLua** [comment]
Thanks, @Dpbm for all your hard work!

I uninstalled and then reinstalled your scripts, and it didn't initially load from my application menu but did load when I ran kindle.sh directly from the console. However, I was expecting to see a view similar to iPad/Android Kindle app, but instead it pulled up the same view that I see when I go to the Kindle website and sign into my account there (which I currently have saved as a bookmark on my Chrome browser). The disadvantage of the Kindle website is that it doesn't allow filtering based on kindle user/device (important since our family shares the same Amazon Kindle login). 

Was the purpose of your app to connect to the Kindle website for its functionality?

**Comment by Dpbm** [comment]
Yeah, actually, when I made this script, the main goal was to be easier to access kindle on desktop. For my use case this approach was the best, but for sure, as it uses the web version, it has a bunch o limitations.

Once you want something closer to the mobile experience, there are some alternatives you could try:

1. Use [Waydroid](https://waydro.id/) to load the `kindle.apk`. It's not that hard, but it can be a little bit trick to find a legit `apk` online. [Here](https://youtu.be/FKnkIf9jb7U)'s a video showing how to install and configure.
2. You can Use an Android emulator, like [genymotion](https://www.genymotion.com/), and install it as it's done in a regular phone.
3. Use [scrcpy](https://github.com/Genymobile/scrcpy) to stream your mobile device screen to your computer.
4. Use [wine](https://www.winehq.org/) to run the [windows version of kindle app](https://www.amazon.com/b?ie=UTF8&node=16571048011).

**Comment by SugarRayLua** [comment]
Thanks, @Dpbm. I've tried the #1 (which seemed it would be the easiest since I use Waydroid for many other applications), but it turns out since I run Waydroid on a x86-64 machine and that most Android apps target arm64, some (like unfortunately the Kindle.apk) don't work well on Waydroid on a x86-64 machine.

Option #4 though seems like a good option to try, thanks!

**Comment by SugarRayLua** [comment]
@Dpbm , @Abhishek99588 ,

I spent some time this weekend seeing if I could get the actual Kindle App for Windows working in Linux and was finally successful. After multiple times trying different versions and installers, it turned out that I found some others who posted the secret on another forum:  Amazon installs and runs an auto-updater that updates the app when you first try to close the app no matter even if you un-check the auto-update setting in the Kindle app!  Thus, I was able to install the Kindle App for Windows in wine, and it would run a few times then crash, and the reason it crashed is that each time it was getting updated to a newer version that finally wouldn't run in wine under Linux. The other individuals who posted that secret also suggested an easy workaround which is working for me and which I submitted to the WineHQ database for others to be aware of (submission under review)

Details:
I couldn't get any Kindle App for Windows version working above 1.39; Kindle App for Windows version 1.31 worked best for me.

My system:
Ubuntu KDE derivative (Tuxedo OS) 24.04 x86-64 AMD

Setup:
I found it easiest to install under the "Bottles" environment (seems easier to install basic wine programs than Lutris).
Thus,
1) Installed "Bottles" (https://usebottles.com) and followed the instructions to setup a new "bottle" (aka wine "prefix")
*I found it best to make the "Bottle" a "custom" prefix and have it use "system-wine (9.0)" [keep default Windows 10]

2) Downloaded Kindle App for Windows 1.31 (I chose to download it from "Uptodown" store: https://en.uptodown.com and search for Kindle App for Windows, older versions)

3) I then followed the instructions in the bottle to "run executable" and used its file selector to run the .exe file downloaded in step 2 above

The Kindle App for Windows will then install and start and give you a registration screen to input your Amazon Kindle account information. After that it will load in your Kindle library and you can choose which ebooks you'd like to download to your Linux device and any modifications to the display setting

4) BEFORE CLOSING The Kindle App for Windows the first time, complete the next steps to prevent the Kindle app from auto-updating to a version which will crash:

5) delete Amazon Kindle "updates" folder locates inside your drive_c inside of whatever prefix you've installed the Kindle app in

(e.g.
WINE_PREFIX\drive_c\users\(YOUR_USER_NAME)\AppData\Local\Amazon\Kindle; easy to do with wine explorer and the "Bottles" app lets you open wine explorer as one of the options if you open "Legacy Wine Tools" when you are in the bottle that you created in step 1 above)

6) navigate back to the same directory Kindle directory that you deleted the "updates" folder above and create an empty file named "updates" to replace the updates directory you deleted in step 5 above

(e.g. WINE_PREFIX\drive_c\users\(YOUR_USER_NAME)\AppData\Local\Amazon\Kindle>
type nul  >updates )

The empty updates file that you create in this step prevents the Kindle app from automatically installing updates that won't work in wine and crash the app (which the Kindle app otherwise tries to do automatically even the first time you attempt to close the app)

Only deficiencies I've found from installing the Kindle App for Windows this way (and why I gave the process a "Silver" and not "Platinum" rating on WineHQ) is that I couldn't use a couple of my ebooks (approximately 5% from small sample size testing). One book that I can easily open from Kindle on the web wouldn't open for some reason in this version of the Kindle App for Windows; another book (new textbook) said I needed to install a newer Kindle App version to open it (which as I explained earlier wouldn't work in wine installation).

Fyi and hope this helps either of you if you decide to try installing the Kindle App for Windows on your Linux machine.

Happy Holiday Season :-)

**Comment by Dpbm** [comment]
Thanks @SugarRayLua! I'm glad to see that you found a solution. 

The tutorial you gave us is very helpful. I'll link it on `readme.md` for those who are facing the same issues.

Thanks again and Happy Holidays🎉🎉

**Comment by SugarRayLua** [comment]
You're welcome and sounds good!

**Comment by billbeans** [comment]
@SugarRayLua, I was really excited to use your solution but damn Amazon wouldn't let me sign in. I entered my email and password, then when it forced me to use 2FA by entering a passcode sent to me via email it told me I entered the wrong number, even though I entered it correctly many times.

I'm using Debian 12 and Wine prompted me to install Gecko before opening the app, maybe this is part of the problem. Very disappointed and annoyed that I have to continue using a Windows VM for Kindle

**Comment by SugarRayLua** [comment]
Hi, @billbeans.
Sorry to hear you were having trouble.

If you are interested, I've found there is another way to use Kindle without Windows VM but requires another VM: Waydroid.
I use Waydroid a lot on my x86_64 machine and like it very much. I can't get most apps to work but Kindle used to be one that I couldn't get to work but now got it working :-). I think I got it working by installing "libhoudini" which actually emulates ARM64 inside of Waydroid for it to work.  If you are interested, here is the Waydroid link:

https://docs.waydro.id/usage/install-on-desktops

and here is one installer script I used to install libhoudini (if Kindle won't load up and work in your standard Waydroid install):

https://github.com/casualsnek/waydroid_script

Fyi,

Have a good rest of your weekend. 

cc: @Dpbm

**Comment by Nitrousoxide** [comment]
> [@SugarRayLua](https://github.com/SugarRayLua), I was really excited to use your solution but damn Amazon wouldn't let me sign in. I entered my email and password, then when it forced me to use 2FA by entering a passcode sent to me via email it told me I entered the wrong number, even though I entered it correctly many times.
> 
> I'm using Debian 12 and Wine prompted me to install Gecko before opening the app, maybe this is part of the problem. Very disappointed and annoyed that I have to continue using a Windows VM for Kindle

I had the same issue.  I solved it by going to my amazon account and setting up an authenticator app to use instead of the sms 2-factor.  When I tried to log in on kindle for windows then I used my auth app's code and it successfully logged me in.

I would note that more recent books appear to not be usable in the OP's suggested version (version 1.31).  Hopefully we can find a version which works on all books.

**Comment by SugarRayLua** [comment]
Sorry @Nitrousoxide & @billbeans , you both seem to have so much trouble with this.

Note that when using Waydroid, I've been able to use the latest Kindle for Android app which I believe lets me download any recent books.

The only bummer I've found about using Waydroid is that so far one cannot only access the internet with it via wifi. That works for most situations, but I've also got cell installed in my laptop for when I'm away from wifi and so far Waydroid is not able to connect via cell signal.

Fyi :-)
